name: Sync code to Hugging face spaces

on:
  push:
    branchs: [main]

  
  workflow_dispatch:


jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Ignore large files
        run : git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch "Rag_Documents/layout-parser-paper.pdf"' HEAD

      - name: Push to hub
        env:
          HF_PUSH_CODE_TOKEN: ${{ secret.HF_PUSH_CODE}}
        run: git push --force https://swapy08:$HF_PUSH_CODE_TOKEN@huggingface.co/spaces/swapy08/E2E-Agentic-AI